"""Create Pricelist and Item tables

Revision ID: d7a46768014a
Revises: 
Create Date: 2022-11-08 19:42:40.141637

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'd7a46768014a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pricelists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('pricelist_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pricelist_id'], ['pricelists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_items_pricelist_id'), 'items', ['pricelist_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_items_pricelist_id'), table_name='items')
    op.drop_table('items')
    op.drop_table('pricelists')
    # ### end Alembic commands ###
